# Generated by Django 5.2.3 on 2025-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_weekly_hours',
            field=models.PositiveIntegerField(default=40, help_text='Number of hours the user works per week.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=0, help_text='Number of hours the user worked per week.'),
        ),
    ]
